#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USER}
#spring.datasource.password=${DB_PASSWORD}

DB_URL=jdbc:mysql://db:3307/taskflow
DB_USER=taskflow_user
DB_PASSWORD=password

server.forward-headers-strategy=native
server.use-forward-headers=true